name: Deploy Code

on:
  push:
    branches:
      - main
env:
  AZURE_SUBSCRIPTION_ID: c6832d86-815e-44ca-9bca-debe61931073   # set this to your Azure Subscription Id
  AZURE_RESOURCE_GROUP: AzureChallengeGithub  # set this to your target resource group
  AZURE_FUNCTIONAPP_NAME: GithubActionas
  APPLICATIONPATH: GitHubActionsChallengeFunctionApp

jobs:
  deploy-virtual-network-template:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.APPLICATIONPATH }}
      - name: Finalizing
        run: |
          echo -e "\033[1;32mPlease use Azure portal or Azure Functions Core Tools to fetch url with keys to invoke the Azure function(s)\033[m"
          echo "func azure functionapp list-functions ${{ env.APPNAME }} --show-keys"
          echo "It may take upto 10 minutes for the function list to update"
