name: Deploy Code

on:
  push:
    branches: [main1]
  workflow_dispatch:
  
env:
  AZURE_RESOURCE_GROUP: 'AzureChallengeGithub'  # set this to your target resource group
  AZURE_FUNCTIONAPP_NAME: 'GithubActionsasdf'
  APPLICATIONPATH: 'GitHubActionsChallengeFunctionApp'
  DOTNET_VERSION: 3.1

jobs:
  deployFunction:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.APPLICATIONPATH }}'
          dotnet build --configuration Release --output ./output
          popd
          
      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.APPLICATIONPATH }}/output
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
